clang_use_chrome_plugins=false
chrome_pgo_phase=0
disable_fieldtrial_testing_config=true
enable_aggressive_tab_discarding=true
enable_backing_store_limit_for_canvas=true
enable_browser_side_navigation=false
enable_hangout_services_extension=false
enable_mdns=false
enable_one_click_signin=false
enable_print_preview=false
enable_remoting=false
enable_reporting=false
enable_service_discovery=false
enable_tab_discarding=true
enable_widevine=true
exclude_unwind_tables=true
google_api_key=""
google_default_client_id=""
google_default_client_secret=""
max_renderer_memory=2048
safe_browsing_mode=0
safebrowsing_enable=false
treat_warnings_as_errors=false
use_official_google_api_keys=false
use_preinstalled_included_apps=false
use_unofficial_version_number=false
v8_drumbrake_bounds_checks=true
